
# ═══════════════════════════════════════════════════════════════
# 🚀 Generated by GitMaxer (Free Plan)
# 🔗 Upgrade at https://gitmaxer.vercel.app for watermark-free code
# ═══════════════════════════════════════════════════════════════

// =============================================================================
// LEARN DOM MANIPULATION AND STRING MANIPULATION WITH ASCII ART GENERATOR
// =============================================================================
//
// Learning Objectives:
// 1. Understand how to select HTML elements using JavaScript (DOM Manipulation).
// 2. Learn how to listen for user interactions (event listeners).
// 3. Practice manipulating strings to create patterns and dynamic content.
// 4. See how to update the content of an HTML element with JavaScript.
//
// This tutorial will guide you through building a simple ASCII art generator.
// You'll take user input and transform it into a text-based art representation.

// --- 1. DOM Manipulation: Getting References to HTML Elements ---
//
// We need to interact with specific parts of our HTML page.
// The `document.getElementById()` method is a fundamental way to select an element
// by its unique `id` attribute. This gives us a JavaScript object representing
// that HTML element, allowing us to read from it or write to it.

// Get a reference to the input field where the user types text.
const textInput = document.getElementById('text-input');

// Get a reference to the button that triggers the art generation.
const generateButton = document.getElementById('generate-button');

// Get a reference to the `div` where we will display our generated ASCII art.
const asciiArtDisplay = document.getElementById('ascii-art-display');


// --- 2. Event Listeners: Responding to User Actions ---
//
// To make our application interactive, we need to detect when the user does
// something, like clicking a button. Event listeners allow us to "listen" for
// specific events (like 'click') on an element and run a function (a callback)
// when that event occurs.

// We're adding an event listener to the `generateButton`.
// When the button is 'click'ed, the function provided will be executed.
generateButton.addEventListener('click', generateAsciiArt);


// --- 3. String Manipulation: The Core of ASCII Art ---
//
// This is where we transform the user's input into art. We'll use basic string
// methods and loops to build our art line by line.

// This function will be called when the generate button is clicked.
function generateAsciiArt() {
  // Get the current text from the input field.
  // `.value` is a property of input elements that holds their current text.
  const inputText = textInput.value;

  // Clear any previous art displayed.
  // Setting `innerHTML` to an empty string effectively removes all child elements.
  asciiArtDisplay.innerHTML = '';

  // Basic string manipulation: Let's create a simple frame and add the text.
  // We'll build the art line by line, storing each line in an array.
  const artLines = [];

  // Define a simple border character.
  const borderChar = '*';
  const paddingChar = ' '; // Character for space inside the border

  // --- String Building Logic ---
  // We'll create a border around the text.
  // First, calculate the width needed for the inner content.
  // The width will be the length of the input text plus some padding.
  const contentWidth = inputText.length + 4; // 2 spaces padding on each side

  // Create the top border line.
  // `borderChar.repeat(contentWidth)` creates a string of `contentWidth` border characters.
  const topBorder = borderChar.repeat(contentWidth);
  artLines.push(topBorder); // Add the top border to our array of lines.

  // Create the middle line with the text.
  // We add padding before and after the text for visual appeal.
  const textLine = `${borderChar}${paddingChar}${inputText}${paddingChar}${borderChar}`;
  artLines.push(textLine); // Add the text line.

  // Create the bottom border line.
  const bottomBorder = borderChar.repeat(contentWidth);
  artLines.push(bottomBorder); // Add the bottom border.

  // --- 4. DOM Manipulation: Updating Display ---
  //
  // Now that we have our art lines (as an array of strings), we need to display
  // them in the `asciiArtDisplay` div.
  //
  // We'll iterate through our `artLines` array. For each line, we'll create a
  // new paragraph element (`<p>`) and set its text content.
  // Finally, we'll append this new paragraph to our display div.

  artLines.forEach(line => {
    // Create a new HTML paragraph element.
    const paragraphElement = document.createElement('p');

    // Set the text content of the paragraph.
    // `textContent` is preferred over `innerHTML` for displaying plain text,
    // as it prevents potential security issues (XSS) if the input contained HTML.
    paragraphElement.textContent = line;

    // Append the newly created paragraph element to the display div.
    asciiArtDisplay.appendChild(paragraphElement);
  });
}

// --- Example Usage ---
//
// To use this code:
// 1. Create an HTML file (e.g., index.html).
// 2. Add the following HTML structure:
//
//    <!DOCTYPE html>
//    <html>
//    <head>
//        <title>ASCII Art Generator</title>
//    </head>
//    <body>
//        <h1>Dynamic ASCII Art Generator</h1>
//        <input type="text" id="text-input" placeholder="Enter text here">
//        <button id="generate-button">Generate Art</button>
//        <div id="ascii-art-display">
//            <!-- ASCII art will appear here -->
//        </div>
//        <script src="your-script-name.js"></script> <!-- Link to this JavaScript file -->
//    </body>
//    </html>
//
// 3. Save this JavaScript code in a file (e.g., `script.js`).
// 4. Make sure the `<script src="...">` in your HTML points to this file.
// 5. Open the HTML file in your web browser.
// 6. Type text into the input box and click "Generate Art".
//
// This simple example demonstrates fundamental DOM and string manipulation,
// the building blocks for more complex web interactions!